<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
        <WasmFingerprintAssets>false</WasmFingerprintAssets>
        <OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BlazorCameraStreamer" Version="3.0.1" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.8" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.8" PrivateAssets="all" />
        <PackageReference Include="MudBlazor" Version="9.5.0" />
        <PackageReference Include="Net.Codecrete.QrCodeGenerator" Version="3.0.0" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="wwwroot\sample-data\weather.json" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Model\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CheckInCommon\CheckInCommon.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Include="wwwroot\images\Error\Error.webp" />
      <None Include="wwwroot\images\images.png" />
    </ItemGroup>

    <ItemGroup>
      <None Include="Dockerfile" />
      <None Include="nginx.conf" />
    </ItemGroup>

</Project>
